[[redirects]]
  from = "/*"
  query = { seo = ":value" }
  to = "/error/404.html"
  status = 404

[[redirects]]
  from = "/*"
  query = { apk = ":value" }
  to = "/error/404.html"
  status = 404

[[redirects]]
  from = "/*"
  query = { slot = ":value" }
  to = "/error/404.html"
  status = 404
